### ISSUE TITLE
Week 1 Day 1 - Internet Fundamentals

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#10]
https://github.com/microsarah/WDI/tree/master/curriculum/week-01/01-internet-fundamentals

Ready for review @carmenejames @amyealmeida

Known issues:

Formatting might need to be tidied up.
Double-check that jump links are working for sections

**Comment by amyealmeida** [comment]
I will review this @carmenejames

**Comment by amyealmeida** [comment]
@sarahholden looks great!  I added comments throughout the lesson-- a couple tips on formatting, and then some places that could use clarification and checks for understanding.  I did my best to estimate timing for each section, but please check to see if my estimations look correct.

All the jump links are now working.

Thanks!
