### ISSUE TITLE
Week 1 Day 1 - Welcome to WDI

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#11]
https://github.com/microsarah/WDI/tree/master/curriculum/week-01/01-welcome-to-wdi

Ready for review @carmenejames @amyealmeida

Known issues:

Might need tidying up
Double-check times and jump links if possible!

**Comment by amyealmeida** [comment]
@carmenejames this one too!

**Comment by carmenejames** [comment]
@sarahholden it looks good sarah holden! I left one comment.

**Comment by sarahholden** [comment]
@carmenejames Updated the content where I saw that comment.

The "topics" chart at the top seems a little different since this session is somewhat of a one-off and I wasn't sure which sections to categorize as "guided practice", etc.

But other than that I think this one should be all set! Ready for final review and to close out.
