### ISSUE TITLE
Week 1 Day 1 - Navigating the Terminal

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#12]
https://github.com/microsarah/WDI/tree/master/curriculum/week-01/01-OS-navigation-terminal

@amyealmeida @carmenejames Ready for review

ID Input/assistance needed:
- Organization of extra resources towards the end (Help with this would be great)
- Exercise input - If linking to an existing exercise that is good-to-go, should I just use a hyperlink, or bring it into the project? For labs that I've edited, what's the best way to include these? Right now I just have placed them in a "Labs" folder.

Known issues:
- Need to double-check jump links
- Make sure timing at top of doc matches timing listen in each heading

**Comment by amyealmeida** [comment]
@carmenejames has got this one!

**Comment by carmenejames** [comment]
@sarahholden The extra resources at the end look great. We want everything in the same repo, so if you find an existing exercise/ lab that is good to go but in a different person's repo, it would be great it you could make a copy of it and title it something descriptive like command-line-extra-practice or command-line-extra-lab. For the labs you've edited, that's right! Maybe name the "Labs" folder "W1D1-Labs" or something like that.

The other additional resources look good as are. I checked all the jump links. Looking great!
