### ISSUE TITLE
Week 1 Day 3 - Get to Know Your Cohort

### ISSUE THREAD

**Issue by microsarah** [microsarah/WDI#14]
https://github.com/microsarah/WDI/blob/master/curriculum/week-01/03-get-to-know-your-cohort/IYRKM_IntroGuide.pdf

@carmenejames @amyealmeida I added a PDF here that a few instructors were using. Is there anything else we should add to this lesson? Ideally I'd like to provide instructors with more activities/suggestions.

**Comment by amyealmeida** [comment]
@microsarah I can take a stab at writing a README with some potential structures for this session!

**Comment by microsarah** [comment]
@amyealmeida did you want me to work on a readme for this? Feel free to assign to me if so :)

**Comment by amyealmeida** [comment]
@microsarah This is pretty low priority compared to the other stuff you're working on, so I will leave it assigned to me! Thank you!
