### ISSUE TITLE
Week 1 HW - Command Line Practice

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#16]
https://github.com/microsarah/WDI/tree/master/curriculum/week-01/homework/01-command-line-practice

@carmenejames @amyealmeida 

Still working on the cumulative HW, but figured I'd send this over for you to review and provide input!

No known issues.

**Comment by carmenejames** [comment]
@amyealmeida I will review this one!

**Comment by carmenejames** [comment]
@sarahholden Hi Sarah, it looks great so far!

**Comment by sarahholden** [comment]
@carmenejames Glad to hear! Thank you.
