### ISSUE TITLE
Week 1 - Weekend Project

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#20]
https://github.com/microsarah/WDI/tree/master/curriculum/week-01/week-one-project

@amyealmeida @carmenejames

This one should be ready for review.

@microsarah Same here! One thing I might be able to use a little assistance with is adding in some additional labs for more advanced students. I saw various labs in the build, but I wasn't sure which ones you were using for the curriculum lessons and which might be extra. Thanks!

Known issues:

- Adding exercises for advanced students (see above)
- I've filled out the readme but there are extra files here (rubric, etc.). Are those new or old?

**Comment by carmenejames** [comment]
@sarahholden thank you, this looks good! We just need one rubric for this one project. I'll make a note to Amy below about that. I am not sure what you mean about the extra labs. We don't need to build out entire extra labs for advanced students, but if they exist, it'll be great to reference them. @microsarah for transparency.

@amyealmeida for the rubric for this project, can we just fill this out by plugging the requirements in? Here is the template: https://github.com/microsarah/WDI/blob/master/resources/templates/projects/template-project-rubric.md

**Comment by sarahholden** [comment]
@carmenejames Perfect, sounds great! I'll update the rubric for this one then we can close this one out.

Thanks!
