### ISSUE TITLE
Week 2 Day 2 - Whiteboarding for Interviews

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#21]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/02-whiteboarding-for-interviews

@carmenejames @amyealmeida 

Ready for Review!

Known issues:
- Formatting might need a touch-up
- Double-check jump links, etc.

**Comment by amyealmeida** [comment]
@sarahholden this looks good! I added a couple of small comments to be addressed and fixed some formatting.  One question is timing-- the times currently add up to 75 minutes instead of 60.  Do you think this lesson can be taught in 60 minutes?

Jump links are all functional.

**Comment by sarahholden** [comment]
@amyealmeida Updated the timing here! I shortened a couple of those exercises and I think that should be sufficient time still for students to practice. 

If everything looks good to you feel free to close this one out!
