### ISSUE TITLE
Week 2 Day 1 - Pseudo Code

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#22]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/01-pseudo-code

@carmenejames @amyealmeida - Ready for Review!!

Known issues:
- 1 note for ID
- Jumplinks need to be added

**Comment by amyealmeida** [comment]
@sarahholden I have reviewed this lesson-- looks great!  I did some minor edits for typos and formatting, and added a couple of comments around timing and flow.  All jump links are fixed.

Regarding your question on Bonus Exercises, yes I would split them in to separate files in the attempt to make things as modular as possible.  That way, they can more easily be linked to in different ways depending on how an instructor chooses to use them.

Thanks!
