### ISSUE TITLE
Week 1 Day 2 - Git and Github Foundations

### ISSUE THREAD

**Issue by amyealmeida** [microsarah/WDI#23]
https://github.com/microsarah/WDI/tree/master/curriculum/week-01/02-git-github-foundations

@microsarah This is your Github lesson that I transferred into the repo.  I left a couple of comments, and also couldn't get the formatting correct on some of the code blocks.  Please review when you get a chance!

**Comment by microsarah** [comment]
@amyealmeida made lots of formatting changes and addressed your comments. This will absolutely take the entire 90 minutes. The students always need extra time to grasp git concepts.

Remaining issues:
- there are 2 images missing from this lesson that are marked under "SME NEEDED" comments. We can add them in once we have them from Eric. We can also add in temp images from the doc, but I wasn't able to find the original images or save the ones that are in the doc.
