### ISSUE TITLE
Week 1 Day 2 - CSS Selector Basics

### ISSUE THREAD

**Issue by amyealmeida** [microsarah/WDI#24]
https://github.com/microsarah/WDI/tree/master/curriculum/week-01/02-css-selector-basics

@microsarah here is your CSS Selector lesson that I have added to the repo.  Looks great-- just added a couple of comments!

Thanks

**Comment by microsarah** [comment]
@amyealmeida resolved all comments except adding a link to the HW– I'm not sure we should do this. I'd like to keep the lessons as modular as possible, and not reference one another. Thoughts?
