### ISSUE TITLE
Week 2 Day 1 - Data Types, Variables, Arrays

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#25]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/01-data-types-variables

@amyealmeida @carmenejames Ready for review!

Known Issues:
- A few notes for ID NEEDED - Jumplinks, Formatting exercises

**Comment by sarahholden** [comment]
@amyealmeida @carmenejames Updated this one, moved some content to another lesson. Should be all set :)

**Comment by sarahholden** [comment]
@amyealmeida Hey Amy! I think this one also needs to be reviewed. I know I updated the link above at one point. There are a couple ID Needed notes.

Thanks!

**Comment by amyealmeida** [comment]
@sarahholden Hi Sarah! I addressed the two ID Needed comments and am going to close this issue.
