### ISSUE TITLE
Week 1 Day 4 - Responsive and Positioning

### ISSUE THREAD

**Issue by microsarah** [microsarah/WDI#26]
Ready for review @carmenejames @amyealmeida 

https://github.com/microsarah/WDI/blob/master/curriculum/week-01/04-responsive-positioning/README.md

**Comment by amyealmeida** [comment]
@microsarah looked this over -- thanks for calling out all the areas for SME support.  My biggest comment was that I'm not sure every Learning Objective was hit during the lesson.  I could have missed something though!

**Comment by microsarah** [comment]
Everything should be up to date– no more SME needed notes. This is ready to close upon final review @amyealmeida.
