### ISSUE TITLE
Week 1 Day 4 - Github Branches, Merging, and Pages

### ISSUE THREAD

**Issue by microsarah** [microsarah/WDI#27]
Ready for review @carmenejames @amyealmeida 

https://github.com/microsarah/WDI/blob/master/curriculum/week-01/04-github-branches-merging-pages/README.md

**Comment by amyealmeida** [comment]
@microsarah this looks good-- I added a couple clarifying questions!

**Comment by microsarah** [comment]
This should be complete now & ready to close @amyealmeida
