### ISSUE TITLE
Week 1 Day 5 - CSS Animations

### ISSUE THREAD

**Issue by microsarah** [microsarah/WDI#28]
https://github.com/microsarah/WDI/tree/master/curriculum/week-01/05-css-animation

@carmenejames @amyealmeida Ready for review.

Known issues:
- SME/Instructor support needed in 2 places
- Lesson may look small but it's very self-driven and includes 2x Independent Practices. Happy to discuss if it needs a change

**Comment by amyealmeida** [comment]
@microsarah just reviewed this one.  I wonder if students might need to do a guided practice with an instructor before diving into the independent practice?

If we don't add a guided practice, I would definitely make sure we have more additional resources for students to refer to as they practice these skills.

**Comment by microsarah** [comment]
Good point. Let's see if Sarah has some resources for this tomorrow and I'll revisit.

**Comment by microsarah** [comment]
Added a transition example and resolved all SME Needed comments. Ready for final review @amyealmeida
