### ISSUE TITLE
Week 1 Day 5: Fonts and Ems

### ISSUE THREAD

**Issue by microsarah** [microsarah/WDI#31]
Ready for review @carmenejames @amyealmeida 

https://github.com/microsarah/WDI/tree/master/curriculum/week-01/05-fonts-ems

Known Issues:
I need to add a few extra resources– can do next week! Marked with SME Needed note.

**Comment by amyealmeida** [comment]
@microsarah I just went through and edited a few things.  Do you think this lesson would take 90 minutes?  Seems like maybe we need an Independent Practice or something at the end.

**Comment by microsarah** [comment]
Makes sense– I'll add an independent practice for Keyframes :)

**Comment by microsarah** [comment]
Added extra resources and an Independent Practice. We should be all set to close this @amyealmeida
