### ISSUE TITLE
Week 2 Day 2 - Control Flow

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#32]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/02_control_flow

@amyealmeida @carmenejames Ready for review!

Known issues:

- Notes for ID NEEDED
- 1 Note for SME NEEDED
- Jump Links / Top chart with timing

**Comment by amyealmeida** [comment]
@sarahholden I have addressed all the ID Needed Notes in this lesson

**Comment by sarahholden** [comment]
@newyork-anthonyng 

Looks great! Go ahead and submit a pull request and merge this one in. Very creative and fun exercise, i love it!

Thanks so much.
