### ISSUE TITLE
Week 2 Day 2 - Arrays & Loops

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#33]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/02-arrays-loops

@amyealmeida @carmenejames Ready For Review!

Known Issues:
- Jump Links / Topics Chart
- Notes for ID NEEDED for formatting examples pulled from Circuits

Thanks!

**Comment by amyealmeida** [comment]
@sarahholden addressed the "ID NEEDED" comments on this lesson!

**Comment by sarahholden** [comment]
Perfect thanks @amyealmeida. I Added 1 SME Needed note here for an exercise where it would be helpful to have a more hands-on activity, but other than that this one should be all set. I've read through and double-checked everything.

Thanks!
