### ISSUE TITLE
Week 2 Day 2 - Functions

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#34]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/02-functions

@amyealmeida @carmenejames Ready for review!

Known issues:

- Jump links / Timing chart at top

**Comment by amyealmeida** [comment]
@sarahholden I have reviewed this-- everything is looking great!

**Comment by carmenejames** [comment]
@amyealmeida Perfect, thank you!

**Comment by sarahholden** [comment]
@amyealmeida Perfect! Thank you!

**Comment by sarahholden** [comment]
Made a handful of updates here and everything should be all set. Closing this one out.
