### ISSUE TITLE
Week 2 Day 3- Objects

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#35]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/03_objects

@carmenejames @amyealmeida Ready for review!

Known issues:
- Jumplinks / Topic chart needs to be set up
- A couple notes for "ID Needed"

**Comment by amyealmeida** [comment]
I went through and made formatting changes for the exercises and added the jumplinks.  

For one "ID NEEDED" note, I wasn't sure the best way to format the exercise.  Not sure if the solution should be in a separate file in the folder that is then linked to?

**Comment by sarahholden** [comment]
Thanks Amy!

Made a couple last updates and moved that solution to another file.

This one should be all set!
