### ISSUE TITLE
Week 2 Day 4 - OOP

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#36]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/04-oop-in-js

@carmenejames @amyealmeida 

Known Issues:
- 1 ID Needed
- 1 SME Needed

Thanks! :)

**Comment by amyealmeida** [comment]
@sarahholden I've addressed the comments here!

**Comment by sarahholden** [comment]
@newyork-anthonyng 

Looks amazing! Very clean and easy to read and follow. Also, thanks for the small copy edits :)
Go ahead and submit a pull request and merge this in when you get a chance. 

Thank you!
