### ISSUE TITLE
Week 2 - Dev tools and Debugging JS

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#37]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/03_dev_tools_debugging
AND
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/05-dev-tools-debugging

@amyealmeida @carmenejames 

Could use an SME to help pull together/flesh out these lessons and lab.

I've added notes and instructions in https://github.com/microsarah/WDI/tree/master/curriculum/week-02/03_dev_tools_debugging

There's content to work from, but one lab needs to be built out and the other modified for clarity. Also, just general flow of the two lessons.

Let me know if you have questions!

**Comment by sarahholden** [comment]
@newyork-anthonyng 

Looks great! Thanks for working on this one. Great exercises and flow.

1 super small issue:
- Looks like there's a broken image in the Week 2 Day 5 lesson.

Other than that this should be ready for a Pull Request and to be merged.

Thank you!

**Comment by newyork-anthonyng** [comment]
@sarahholden Thanks for catching that. I made the update to fix the broken image.
