### ISSUE TITLE
Week 2 Day 4 - DOM

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#38]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/04-dom-manipulation

@carmenejames @amyealmeida  Ready for Review

Known Issues:
- 2 SME Needed comments
- ID Needed comments (jumplinks, formatting)

Thanks!

**Comment by amyealmeida** [comment]
@sarahholden have addressed ID needed comments!

**Comment by sarahholden** [comment]
Perfect, thanks @amyealmeida!

**Comment by sarahholden** [comment]
@newyork-anthonyng 

Nice! Looks great. Do you mind having that CodePen exercise hosted on your account? I'm not sure if we have a GA codepen account or something, but just wanted to double-check.

Go ahead and submit a Pull Request for this one and merge it in.

Thank you!

**Comment by newyork-anthonyng** [comment]
@sarahholden No problem; I don't mind hosting the exercise on my CodePen account.
