### ISSUE TITLE
Week 2 Day 5 - JS Events

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#40]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/05-js-events

@amyealmeida @carmenejames Ready for review!

Known issues:
- 1 note for ID needed
- 1 note for SME needed (potentially)
- Would be great to have someone double-check links to starter code exercises/instructor demos. I checked them all as I went along, but nothing worse than a 404 error when looking for something!

Thanks!

**Comment by amyealmeida** [comment]
@sarahholden I have updated the timing chart and fixed one broken jump link!

**Comment by sarahholden** [comment]
Awesome, thank you Amy! Really appreciate your updating those timing charts and making sure everything is hooked up :)

Went through and double-checked and i believe this one is ready to close out as well!
