### ISSUE TITLE
Week 2 Day 1 - Intro to JS

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#42]
https://github.com/microsarah/WDI/tree/master/curriculum/week-02/01-intro-js

@amyealmeida @carmenejames Ready for review!

Known issues:
- 1 ID NEEDED note

Thank you!

**Comment by amyealmeida** [comment]
@sarahholden This looks good.  My only question is if this is a full 90 minute lesson?  The timing you put next to different sections only adds up to about an hour.  Thanks!

**Comment by sarahholden** [comment]
@amyealmeida Great question! There was quite a bit of material for the other session that afternoon that seemed difficult to fit into 90 minutes, so I made that one longer and this one shorter since that seemed to make sense. Let me know if I should rearrange somehow or move some content over from the other lesson! Here it is for reference: 

https://github.com/microsarah/WDI/tree/master/curriculum/week-02/01-data-types-variables

**Comment by sarahholden** [comment]
@amyealmeida I know we chatted about this one in our meeting and it seems okay that this lesson is shorter since the other afternoon session is a bit longer. Let me know if that's not the case!

Double-checked everything and closing this one out for now!
