### ISSUE TITLE
Week 3 Day 1 - jQuery vs. JavaScript

### ISSUE THREAD

**Issue by sarahholden** [microsarah/WDI#43]
https://github.com/microsarah/WDI/tree/master/curriculum/week-03/01_jquery_vs_javascript

@amyealmeida @carmenejames Ready for review!

1 ID NEEDED note

Thanks!

**Comment by amyealmeida** [comment]
@sarahholden thanks! I just want to confirm what lesson this is because the title doesn't match anything we have on the Build Doc.  Is this the first morning session of Week 3, Day 1?  Directly preceding Intro to jQuery?

**Comment by sarahholden** [comment]
@amyealmeida Hey Amy! So it was in the build doc for Week 2 day 4 morning session (Ice Breaker: Native vs. jQuery Discussion), but it seemed to make more sense to move it to the day we introduce jQuery so that students will have a point of reference and have already seen how to manipulate the DOM using native JavaScript since students haven't covered the DOM at all by the Week 2 day 4 morning session.

**Comment by amyealmeida** [comment]
@sarahholden thanks for the clarification! I just updated the organization a little and added a time table at the top. I'm going to close this.
