### ISSUE TITLE
Week 1 Day 3 - Box Model & Flexbox

### ISSUE THREAD

**Issue by microsarah** [microsarah/WDI#7]
https://github.com/microsarah/WDI/tree/master/curriculum/week-01/03-box-model-flexbox

Ready for review @carmenejames @amyealmeida 

Known issues: 
- SME input needed in 3 places
- 'Hungry for more' section isn't using link titles (markdown issue)
- Time not entered for each section of lesson, need ID assistance

**Comment by amyealmeida** [comment]
I'm reviewing this too @carmenejames

**Comment by microsarah** [comment]
FYI @amyealmeida fixed 2 known issues:
- 'Hungry for more' section isn't using link titles (markdown issue)
- Time not entered for each section of lesson, need ID assistance

**Comment by amyealmeida** [comment]
@microsarah This lesson has been reviewed! I added a couple of comments.  One thing that could be added are a couple checks-for-understanding throughout the lesson.

Thanks!

**Comment by microsarah** [comment]
Made some changes per your comments @amyealmeida– thank you! Sending this out for instructor input.

**Comment by microsarah** [comment]
We should be good to close this one, @amyealmeida. Feel free to do a final review :)
