### ISSUE TITLE
Week 1 Day 3 - Design Challenge Lab

### ISSUE THREAD

**Issue by microsarah** [microsarah/WDI#8]
https://github.com/microsarah/WDI/tree/master/curriculum/week-01/03-design-css-challenge-lab

Ready for SME input - notes in comments (viewable in raw file).

**Comment by microsarah** [comment]
Lab complete using work from Sarah Holden. @amyealmeida this is ready to review & close.

**Comment by amyealmeida** [comment]
@microsarah I just realized that this is the same as @sarahholden 's  Homework Part 2.  

Is there anything else we can replace this with?

**Comment by microsarah** [comment]
Amy and I discussed the comment above and the material being covered is different. I adjusted some language to make the lab more student-facing.
